services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Waldhacker\Hooksie\:
    resource: '../Classes/*'

  Waldhacker\Hooksie\Controller\ListController:
    public: true

  Waldhacker\Hooksie\Listener\EventListener:
    tags:
      - name: event.listener
        identifier: 'myListener'
        event: TYPO3\CMS\Core\Mail\Event\AfterMailerInitializationEvent

  Waldhacker\Hooksie\DataHandler\PostProcessor:
    public: true

  Waldhacker\Hooksie\Events\RecordCreatedEvent:
    tags:
      - name: hooksie.hookable
        label: 'LLL:EXT:dashboard/Resources/Private/Language/locallang.xlf:widgets.sysLogErrors.title'
        description: 'LLL:EXT:dashboard/Resources/Private/Language/locallang.xlf:widgets.sysLogErrors.description'

  Waldhacker\Hooksie\Events\RecordUpdatedEvent:
    tags:
      - name: hooksie.hookable
        label: 'Record Updated'
        description: 'Description'
