services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Waldhacker\Hooky\:
    resource: '../Classes/*'

  Waldhacker\Hooky\Controller\ListController:
    public: true

  Waldhacker\Hooky\Listener\EventListener:
    tags:
      - name: event.listener
        identifier: 'myListener'
        event: TYPO3\CMS\Core\Mail\Event\AfterMailerInitializationEvent

  Waldhacker\Hooky\DataHandler\PostProcessor:
    public: true

  Waldhacker\Hooky\Events\RecordCreatedEvent:
    tags:
      - name: hooky.hookable
        label: 'LLL:EXT:hooky/Resources/Private/Language/hooky.xlf:event.recordCreated.label'
        description: 'LLL:EXT:hooky/Resources/Private/Language/hooky.xlf:event.recordCreated.description'

  Waldhacker\Hooky\Events\RecordUpdatedEvent:
    tags:
      - name: hooky.hookable
        label: 'LLL:EXT:hooky/Resources/Private/Language/hooky.xlf:event.recordUpdated.label'
        description: 'LLL:EXT:hooky/Resources/Private/Language/hooky.xlf:event.recordUpdated.description'


  Waldhacker\Hooky\Commands\QueueHooksCommand:
    tags:
      - name: 'console.command'
        command: 'hooky:hooks:queue'
        description: 'Convert triggered events in corresponding hook messages'


  Waldhacker\Hooky\Commands\SendCommand:
    tags:
      - name: 'console.command'
        command: 'hooky:hooks:send'
        description: 'Send hooks from queue'

  querybuilder.tx_hooky_hook:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'tx_hooky_hook'

  Waldhacker\Hooky\Repository\HookConfigurationRepository:
      arguments:
        - '@querybuilder.tx_hooky_hook'

  Waldhacker\Hooky\ViewHelpers\JsonDecodeViewHelper:
    public: true
